### ISSUE TITLE
关于Eval的结果

### ISSUE THREAD

**Issue by donggoing** [TencentYoutuResearch/CrowdCounting-P2PNet#11]
我直接训练最好得到54，但是我用给出的权重（51.9，阈值保持默认为0.5）跑出来是53.13，但是阈值改成0.45是可以到52的，请问51.9是在当前代码默认setting下训练出来的还是有所调整呢？
如果是在当前代码下跑出来的，请问能给一下你们的SHTechA的数据集和组织格式吗？因为我只改了loader。

**Comment by wangrui9** [comment]
你好，我也有一些训练的问题，再经过issue里好心人的解答，我得到了SHHA，训练了3500轮，第1125轮获得了best mae53.13
我的问题是，为什么p2p网络训练一轮SHHA只需要十几秒，这比其他网络快太多了，第二个问题是获得不了原论文中的精度，第三个问题是作者给的参数中让训练3500轮为什么训练了1000多轮之后就无法再获得更好的精度，最后一个问题是为什么网络训练到后面的epoch时maemse指标表现的特别差
可以交流一下你的看法吗，感谢你任何回复！

**Comment by SDarknessZX** [comment]
我想问一下train_list的文件和test_list文件是怎么得到的呢？？

**Comment by SDarknessZX** [comment]
> 你好，我也有一些训练的问题，再经过issue里好心人的解答，我得到了SHHA，训练了3500轮，第1125轮获得了best mae53.13 我的问题是，为什么p2p网络训练一轮SHHA只需要十几秒，这比其他网络快太多了，第二个问题是获得不了原论文中的精度，第三个问题是作者给的参数中让训练3500轮为什么训练了1000多轮之后就无法再获得更好的精度，最后一个问题是为什么网络训练到后面的epoch时maemse指标表现的特别差 可以交流一下你的看法吗，感谢你任何回复！

你好，我想问一下你的SHHA怎么得到的呢？？能给我看一下代码嘛？？

**Comment by wangrui9** [comment]
你看一下close的issue里面有个人分享了他的代码

**Comment by donggoing** [comment]
> 你好，我也有一些训练的问题，再经过issue里好心人的解答，我得到了SHHA，训练了3500轮，第1125轮获得了best mae53.13 我的问题是，为什么p2p网络训练一轮SHHA只需要十几秒，这比其他网络快太多了，第二个问题是获得不了原论文中的精度，第三个问题是作者给的参数中让训练3500轮为什么训练了1000多轮之后就无法再获得更好的精度，最后一个问题是为什么网络训练到后面的epoch时maemse指标表现的特别差 可以交流一下你的看法吗，感谢你任何回复！

请问你用作者给的权重能跑出report的结果吗？

**Comment by donggoing** [comment]
> 你好，我也有一些训练的问题，再经过issue里好心人的解答，我得到了SHHA，训练了3500轮，第1125轮获得了best mae53.13 我的问题是，为什么p2p网络训练一轮SHHA只需要十几秒，这比其他网络快太多了，第二个问题是获得不了原论文中的精度，第三个问题是作者给的参数中让训练3500轮为什么训练了1000多轮之后就无法再获得更好的精度，最后一个问题是为什么网络训练到后面的epoch时maemse指标表现的特别差 可以交流一下你的看法吗，感谢你任何回复！

还有就是，我觉得这里有问题 https://github.com/TencentYoutuResearch/CrowdCounting-P2PNet/issues/10#issue-1044295739 ，这样导致偏移分支没有得到训练，但是竟然还能训练到54，有点神奇的

**Comment by wangrui9** [comment]
没有跑出论文中的指标，我没发现代码还有这样的问题，我仔细看一下

**Comment by SDarknessZX** [comment]
regression = self.regression(features_fpn[1]) * 100 # 8x
您好这句代码为什么要乘100？？我不太明白。。


> 我直接训练最好得到54，但是我用给出的权重（51.9，阈值保持默认为0.5）跑出来是53.13，但是阈值改成0.45是可以到52的，请问51.9是在当前代码默认setting下训练出来的还是有所调整呢？ 如果是在当前代码下跑出来的，请问能给一下你们的SHTechA的数据集和组织格式吗？因为我只改了loader。

**Comment by donggoing** [comment]
> regression = self.regression(features_fpn[1]) * 100 # 8x 您好这句代码为什么要乘100？？我不太明白。。
> 
> > 我直接训练最好得到54，但是我用给出的权重（51.9，阈值保持默认为0.5）跑出来是53.13，但是阈值改成0.45是可以到52的，请问51.9是在当前代码默认setting下训练出来的还是有所调整呢？ 如果是在当前代码下跑出来的，请问能给一下你们的SHTechA的数据集和组织格式吗？因为我只改了loader。

论文里的超参γ

**Comment by SDarknessZX** [comment]
> 我直接训练最好得到54，但是我用给出的权重（51.9，阈值保持默认为0.5）跑出来是53.13，但是阈值改成0.45是可以到52的，请问51.9是在当前代码默认setting下训练出来的还是有所调整呢？ 如果是在当前代码下跑出来的，请问能给一下你们的SHTechA的数据集和组织格式吗？因为我只改了loader。

我训练的最好是53.09。能加个微信交流一下吗

**Comment by SDarknessZX** [comment]
> 我直接训练最好得到54，但是我用给出的权重（51.9，阈值保持默认为0.5）跑出来是53.13，但是阈值改成0.45是可以到52的，请问51.9是在当前代码默认setting下训练出来的还是有所调整呢？ 如果是在当前代码下跑出来的，请问能给一下你们的SHTechA的数据集和组织格式吗？因为我只改了loader。

我的微信是DZX_LBYLM

**Comment by AOTY-szy** [comment]
> > 你好，我也有一些训练的问题，再经过issue里好心人的解答，我得到了SHHA，训练了3500轮，第1125轮获得了best mae53.13 我的问题是，为什么p2p网络训练一轮SHHA只需要十几秒，这比其他网络快太多了，第二个问题是获得不了原论文中的精度，第三个问题是作者给的参数中让训练3500轮为什么训练了1000多轮之后就无法再获得更好的精度，最后一个问题是为什么网络训练到后面的epoch时maemse指标表现的特别差 可以交流一下你的看法吗，感谢你任何回复！
> 
> 还有就是，我觉得这里有问题 [#10 (comment)](https://github.com/TencentYoutuResearch/CrowdCounting-P2PNet/issues/10#issue-1044295739) ，这样导致偏移分支没有得到训练，但是竟然还能训练到54，有点神奇的

因为匹配的点一直在换，所以偏移分支的loss其实是一直在震荡，没有降下去。而且锚点的数量非常多，所以MAE还是靠分类降低下去的。
