### ISSUE TITLE
could u plz tell me where can I get QNRF dataset? The official dataset website seems unavaliable..

### ISSUE THREAD

**Issue by Tracyummy** [TencentYoutuResearch/CrowdCounting-P2PNet#13]

**Comment by Tracyummy** [comment]
Or could u share QNCF dataset through google drive or other ways? Thanks a lot!

**Comment by wzhiyuan2016** [comment]
> Or could u share QNCF dataset through google drive or other ways? Thanks a lot!
You can provide your email address to me and I will send it to you. The total data size is 4.23G

**Comment by wzhiyuan2016** [comment]
> Or could u share QNCF dataset through google drive or other ways? Thanks a lot!

You can provide your email address to me and I will send it to you. The total data size is 4.23G

**Comment by Tracyummy** [comment]
18742518667@163.com
Thanks a lot！

**Comment by wzhiyuan2016** [comment]
> [18742518667@163.com](mailto:18742518667@163.com) Thanks a lot！

Datas has been sent
