### ISSUE TITLE
How to resolve "out of memory" during evaluate on high resolution single image?

### ISSUE THREAD

**Issue by Tracyummy** [TencentYoutuResearch/CrowdCounting-P2PNet#17]
https://github.com/TencentYoutuResearch/CrowdCounting-P2PNet/blob/5c91a81ca062b1c7fd3db3ad1c55b1c21f0a7455/train.py#L187
As I run code above, an error "out of memory" pops while I run the script on single gpu RTX6000 with 24G memory.

**Comment by jhw55** [comment]
Are solved the problem?I had meet it,too.

**Comment by jhw55** [comment]
Are you solved the problem?I had meet it,too.
