### ISSUE TITLE
Convert to ONNX

### ISSUE THREAD

**Issue by XavierGeerinck** [TencentYoutuResearch/CrowdCounting-P2PNet#20]
Hi all!

I'd love to use this model in our ONNX flows but wasn't able to convert it to ONNX. Is there any known way of converting this model to ONNX?

Code I am using:

```python
import os
import sys
import torch

sys.path.append(os.path.abspath(f"{os.getcwd()}/model"))

# Available after the above append
# it's in the model folder
from model.models.p2pnet import P2PNet
from model.models.backbone import Backbone_VGG

def main():
    onnx_model_name = sys.argv[1] or "model"
    onnx_model_name = f"{onnx_model_name}.onnx"

    print("Loading Model")
    # Create the model
    model_backbone = Backbone_VGG("vgg16_bn", True)
    model = P2PNet(model_backbone, 2, 2)

    # Load Weights
    checkpoint = torch.load("./model/weights/SHTechA.pth", map_location=torch.device('cpu'))
    model.load_state_dict(checkpoint["model"])
    model.eval() # Put in inference mode
    
    # Create dummy input
    dummy_input = torch.randn(1, 3, 640, 640)
    # dummy_input1 = torch.randn(1, 3, 1024, 1024)
    # dummy_input = (dummy_input0, dummy_input1)

    # Export as ONNX
    print(f"Exporting as ONNX: {onnx_model_name}")
    torch.onnx._export(
        model,
        dummy_input,
        onnx_model_name, # Output name
        opset_version=13, # ONNX Opset Version
        export_params=True, # Store the trained parameters in the model file
        do_constant_folding=True, # Execute constant folding for optimization
        input_names = ['input'],   # the model's input names 
        # output_names = ['pred_logits', 'pred_points'], # the model's output names (see forward in the architecture)
        output_names = ['pred_logits', 'pred_points'], # the model's output names (see forward in the architecture)
        dynamic_axes={
            # Input is an image [batch_size, channels, width, height]
            # all of it can be variable so we need to add it in dynamic_axes
            'input': {
                0: 'batch_size',
                1: 'channels',
                2: 'width',
                3: 'height'
            }, 
            'pred_logits': [0, 1, 2],
            'pred_points': [0, 1, 2],
        } 
    )


if __name__ == "__main__":
    main()

```

Error I receive:

```
[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Add node. Name:'Add_88' Status Message: Add_88: right operand cannot broadcast on dim 1 LeftShape: {1,40960,2}, RightShape: {1,25600,2}
```

![image](https://user-images.githubusercontent.com/591282/151797045-1478ae1a-6eb0-482f-85a3-4c133dd12741.png)

**Comment by XavierGeerinck** [comment]
Closed, resolved it by processing the output

**Comment by fanweiya** [comment]
How do you deal with this problem, can you provide the code? thks

> Closed, resolved it by processing the output

**Comment by YAwei666** [comment]
> Closed, resolved it by processing the output

@XavierGeerinck hello, how did  you solved this problem? I use your convert onnx code, and encounter this problem, too. can you share your method with me, thanks.

**Comment by KunMengcode** [comment]
@YAwei666  You can view [P2Pnet_onnx](https://github.com/y-1111-y/P2Pnet_onnx)

**Comment by yuxiaoz** [comment]
> > Closed, resolved it by processing the output
> 
> [@XavierGeerinck](https://github.com/XavierGeerinck) hello, how did you solved this problem? I use your convert onnx code, and encounter this problem, too. can you share your method with me, thanks.

It seems that the input axes of height and width cannot be dynamic.

**Comment by harshvardhan2707** [comment]
> > > Closed, resolved it by processing the output
> > 
> > 
> > [@XavierGeerinck](https://github.com/XavierGeerinck) hello, how did you solved this problem? I use your convert onnx code, and encounter this problem, too. can you share your method with me, thanks.
> 
> It seems that the input axes of height and width cannot be dynamic.

I do not understand why can't it be dynamic? Like what I understand is, all that is happening is the final output shape is 1, HxWx4/64, 2 for both pred_points and pred_logits, but it is still not dynamic in nature? Make it make sense
