### ISSUE TITLE
您好，我也是一样的情况，在出现了Namespace(backbone='vgg16_bn', gpu_id=0, line=2, output_dir='./logs/', row=2, weight_path='./weights/SHTechA.pth')之后，后面就没有反应了。不知道有没有顺利解决这个问题的

### ISSUE THREAD

**Issue by fatakWang** [TencentYoutuResearch/CrowdCounting-P2PNet#49]
您好，我也是一样的情况，在出现了Namespace(backbone='vgg16_bn', gpu_id=0, line=2, output_dir='./logs/', row=2, weight_path='./weights/SHTechA.pth')之后，后面就没有反应了。不知道有没有顺利解决这个问题的

_Originally posted by @fatakWang in https://github.com/TencentYoutuResearch/CrowdCounting-P2PNet/issues/16#issuecomment-1364650983_

**Comment by fatakWang** [comment]
我已经解决了这个问题，问题出在我的cuda版本安装的是11.6，然而我却按照readme的指示安装了pytorch1.5的版本，然而pytorch1.5只支持cuda10.2的，所以在model.to(cuda)时卡住了，在我使用与cuda11.6对应的pytorch后，并且在目录下修建一个logs的文件夹之后，就可以跑了

**Comment by qiqihuang** [comment]
楼上 正解
