### ISSUE TITLE
Pretrained VGG weights

### ISSUE THREAD

**Issue by ricardborras** [TencentYoutuResearch/CrowdCounting-P2PNet#5]
Hello, 

thanks for uploading the code!

When trying to run a test using supplied pretrained Shanghai Dataset Part A, an error is raised about VGG_BN pretrained weights:

No such file or directory: '/apdcephfs/private_changanwang/checkpoints/vgg16_bn-6c64b313.pth

Could you share it?

Thanks

**Comment by dahaigui** [comment]
> Solved by downloading 'https://download.pytorch.org/models/vgg16_bn-6c64b313.pth' and pointing vgg16_bn path to downloaded file

Which directory should I put this file in?
