### ISSUE TITLE
How to run model on video input?

### ISSUE THREAD

**Issue by mariosconsta** [TencentYoutuResearch/CrowdCounting-P2PNet#52]
Hello, thank you for this project. My question is, how can I have a video input instead of a single image? I would like to test it with a video or a webcam in real time.

**Comment by zaki1003** [comment]
I added video prediction in my code you can check it in my repository :
https://github.com/zaki1003/CrowdCounting-P2PNet

I also added an explanation and a demo in the Readme.

**Comment by mariosconsta** [comment]
Thank you @zaki1003 !
