### ISSUE TITLE
Softmax Normalization Missing in ClassificationModel

### ISSUE THREAD

**Issue by Younger330** [TencentYoutuResearch/CrowdCounting-P2PNet#66]
It seems that you have overlooked softmax in the ClassificationModel. However, your paper states, "it outputs the confidence scores with a Softmax normalization." I would like to know which statement is accurate.

**Comment by KRK11** [comment]
> It seems that you have overlooked softmax in the ClassificationModel. However, your paper states, "it outputs the confidence scores with a Softmax normalization." I would like to know which statement is accurate.

The code has softmax for ClassificationModel, which can be found in matcher.py.

**Comment by Younger330** [comment]
> > It seems that you have overlooked softmax in the ClassificationModel. However, your paper states, "it outputs the confidence scores with a Softmax normalization." I would like to know which statement is accurate.
> 
> The code has softmax for ClassificationModel, which can be found in matcher.py.

Thanks, it's really helpful.
